server:
  port: 8081
spring:
  datasource:
    url: 'jdbc:sqlite:D:\\520\\projects\\personalCloudDisk\\server\\src\\main\\resources\\data.db'
    driver-class-name: org.sqlite.JDBC

mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
  type-aliases-package: com.xiaohei.personalclouddisk.server.dao
